# Generated by Django 5.2.6 on 2025-09-16 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
