# Generated by Django 5.2.6 on 2025-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0002_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Email",
            field=models.EmailField(max_length=254),
        ),
    ]
