# Generated by Django 5.2.6 on 2025-09-18 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0003_alter_contact_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=122)),
                ("contact_no", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=150)),
                ("car_name", models.CharField(max_length=122)),
                ("model", models.CharField(max_length=14)),
                ("year", models.CharField(max_length=254)),
                ("price", models.CharField(max_length=20)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Well", "Well"),
                            ("Average", "Average"),
                            ("Not Good", "Not Good"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="car_images/")),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
