# Generated by Django 5.2.6 on 2025-09-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0004_sell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
    ]
