# Generated by Django 5.2.6 on 2025-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0005_alter_sell_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=122)),
                ("contact_no", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=150)),
                ("car_name", models.CharField(max_length=122)),
                ("model", models.CharField(max_length=14)),
                ("year", models.CharField(max_length=254)),
                ("price", models.CharField(max_length=20)),
                ("services", models.TextField()),
            ],
        ),
    ]
