# Generated by Django 5.2.6 on 2025-09-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0006_carservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carservice",
            name="price",
        ),
    ]
