# Generated by Django 5.2.6 on 2025-09-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0008_cart_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="cars/")),
            ],
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="car_image",
            field=models.ImageField(blank=True, null=True, upload_to="wishlist/"),
        ),
    ]
