# Generated by Django 5.2.6 on 2025-09-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0009_car_alter_wishlist_car_image"),
    ]

    operations = []
