# Generated by Django 5.2.6 on 2025-09-18 15:33

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ("CarCompanyApp", "0010_auto_20250918_2057"),
#     ]

#     operations = []
from django.db import migrations

def create_cars(apps, schema_editor):
    Car = apps.get_model("CarCompanyApp", "Car")

    cars_data = [
        {
            "name": "Ford Mustang",
            "description": "Iconic sports car with modern performance",
            "price": 20000000,
            "image": "cars/car1.webp",
            # "is_new": True,
        },
        {
            "name": "Tesla Model S",
            "description": "High-performance electric car with autopilot",
            "price": 10000000,
            "image": "cars/car2.jpeg",
            # "is_new": True,
        },
        {
            "name": "Toyota Camry",
            "description": "Reliable, comfortable, and fuel-efficient",
            "price": 3000000,
            "image": "cars/car3.avif",
            # "is_new": True,
        },
        {
            "name": "Honda Accord",
            "description": "Smooth ride with advanced safety features",
            "price": 16000000,
            "image": "cars/car4.avif",
            # "is_new": True,
        },
        {
            "name": "Audi A6",
            "description": "Luxury sedan with advanced tech and comfort",
            "price": 10700000,
            "image": "cars/car5.webp",
            # "is_new": True,
        },
        {
            "name": "BMW X5",
            "description": "Luxury SUV combining performance and style",
            "price": 5000000,
            "image": "cars/car6.jpeg",
            # "is_new": True,
        },
        {
            "name": "Mercedes-Benz C-Class",
            "description": "Elegant design with cutting-edge technology",
            "price": 100000000,
            "image": "cars/car7.avif",
            # "is_new": True,
        },
        {
            "name": "Land Rover Discovery",
            "description": "Perfect SUV for adventure and luxury",
            "price": 30000000,
            "image": "cars/car8.avif",
            # "is_new": True,
        },
        {
            "name": "Maruti Swift 2019",
            "description": "Well-maintained hatchback with great mileage",
            "price": 6000000,
            "image": "cars/used1.jpeg",
            # "is_new": False,
        },
        {
            "name": "Hyundai i20 2020",
            "description": "Premium hatchback with advanced features",
            "price": 4000000,
            "image": "cars/used2.jpeg",
            # "is_new": False,
        },
        {
            "name": "Honda City 2018",
            "description": "Reliable sedan with great comfort",
            "price": 350000,
            "image": "cars/used3.jpeg",
            # "is_new": False,
        },
        {
            "name": "Mahindra Scorpio 2017",
            "description": "Powerful SUV for family and adventure",
            "price": 400000,
            "image": "cars/used4.jpeg",
            # "is_new": False,
        },
    ]

    for car_data in cars_data:
        Car.objects.create(**car_data)


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0010_auto_20250918_2057"),  # adjust if needed
    ]

    operations = [
        migrations.RunPython(create_cars),
    ]
