# Generated by Django 5.2.6 on 2025-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCompanyApp", "0011_seed_cars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
